<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action='../controllers/ajoutStock.php' method="post">

<input type="text" name="quantite" placeholder="inscrivez la quantité du produit">

<input type="text" name="nom" placeholder="inscrivez le nom du produit">

<input type="text" name="ref" placeholder="inscrivez la référence du produit">

<input type="text" name="prixUnitaire" placeholder="inscrivez le prix unitaire">

<input type="submit">


</form>


<a href="../controllers/pageConnecteeSociete.php">home</a>

    
</body>
</html>