<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/ajoutStock.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<section id="contener">
<header>
    
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>

<form action='../controllers/ajoutStock.php' method="post">

<input type="text" name="quantite" placeholder="inscrivez la quantité du produit">

<input type="text" name="nom" placeholder="inscrivez le nom du produit">

<input type="text" name="ref" placeholder="inscrivez la référence du produit">

<input type="text" name="prixUnitaire" placeholder="inscrivez le prix unitaire">

<button class="bouton" type="submit"><span></span><span></span><span></span><span></span>Ajouter</button>


</form>

</section>
    
</body>
</html>