<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action='../controllers/ajoutStock.php' method="post">

<input type="text" name="quantite" placeholder="inscrivez le nom de votre employé ">

<input type="text" name="nom" placeholder="inscrivez le prénom de votre employé ">

<input type="text" name="ref" placeholder="inscrivez le numéro de référence de votre employé">

<input type="text" name="prixUnitaire" placeholder="inscrivez l'email de votre employé">

<input type="submit">


</form>


<a href="../controllers/pageConnecteeSociete.php">home</a>

    
</body>
</html>