<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="../controllers/ajoutClient.php" method="post"> 

<input type="text" name="nom" placeholder="inserez le nom de votr client "> 

<input type="text" name="prenom" placeholder="inserez le prenom de votr client "> 

<input type="text" name="telephone" placeholder="numéro de téléphone du client"> 

<input type="text" name="ref" placeholder="référence client">

<input type="text" name="adresse" placeholder="adresse du client"> 

<input type="text" name="ville" placeholder="ville du client"> 

<input type="text" name="codePostal" placeholder="codePostal du client"> 

<input type="submit">


</form>

<a href="../controllers/pageConnecteeSociete.php">home</a>

</body>
</html>