<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<form action="../controllers/recupObjetSelect.php" method="get">

<?php if(count($tabObjet)>0) :?>

    

<select name="idObjet">
<?php foreach($tabObjet as $objet) :?>
    
<option value="<?= intval($objet['id_stock'])?>"><?= htmlspecialchars($objet['nom_Produit'])?></option>
<?php endforeach ?> 

</select>

<select name="idFacture">

    
<option value="<?= intval($_GET['id'])?>"><?= htmlspecialchars($_GET['id'])?></option>





</select>


<input type="submit">

</form>

<?php endif ?>
    
</body>
</html>