<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="../controllers/connexionSociete.php" method="post"> 

<input type="text" name="nom" placeholder="Nom de votre société"> 

<input type="password" name="password" placeholder="entrez votre mot de passe"> 

<input type="submit">


</form>



</body>
</html>