<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/connexionSociete.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<section id="connexion">
<form action="../controllers/connexionSociete.php" method="post"> 

<input type="text" name="nom" placeholder="Nom de votre société"> 

<input type="password" name="password" placeholder="entrez votre mot de passe"> 

<button type="submit" class="bouton"><span></span><span></span><span></span><span></span>Connexion</button>


</form>
</section>


</body>
</html>