<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/connexionSociete.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    
    <title>Document</title>
</head>
<body>
<section id="connexion">
<form action="../controllers/connexionSociete.php" method="post"> 

<input type="text" name="nom" placeholder="Nom de votre société"> 

<input type="password" name="password" placeholder="entrez votre mot de passe"> 

<button type="submit" class="bouton"><span></span><span></span><span></span><span></span>Connexion</button>

<?php if( !empty($_POST) AND $user==false):?>

<p class="Login">identifiants incorrectes</p>

<?php endif ?>



</form>
</section>



</body>
</html>