<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>


<?php if (count($infosClient) > 0) : ?>

   



<section>

<?php foreach ($infosClient as $client) : ?>

<div>

        <h1> Fiche client </h1>

    <h1>Nom:<?= ($client['nom']) ?></h1>

    <h2>Prénom:<?= ($client['prenom']) ?></h2>

    <h3>Référence:<?= ($client['ref_client']) ?></h3>

    <p>téléphone:<?= ($client['telephone']) ?></p>

    <p>email:<?= ($client['email']) ?></p>

    <p>adresse:<?= ($client['adresse']) ?></p>

    <p>ville:<?= ($client['ville']) ?></p>

    <p>code postal:<?= ($client['CodePostal']) ?></p>

    <div>

    <h1>liste des facture appartenant au client</h1>

    </div>

<a href="../controllers/listeFactureClient.php?id=<?= intval($client['id_clients']) ?>">liste des factures pour ce client </a> 
<br>
<a href="../controllers/creationFacture2.php?id=<?= intval($client['id_clients']) ?>">créer une facture pour ce client </a> 

</div>

<?php endforeach; ?>

</section>

<?php endif ?>

</body>

</html>