<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="../controllers/creationFacture2.php?id=<?= $client['id_clients'] ?>" method="post">



<Label for="datePaiement"> date de paiement prevu : </Label>
<input type="date" name="datePaiement">

<textarea name="commentaire"></textarea>

<Label for="adresseLivraison">adresse de livraison :</Label>
<input type="text" name="adresseLivraison" value="<?=htmlspecialchars($client['adresse'])?>">

<Label for="villeLivraison">ville de livraison :</Label>
<input type="text" name="villeLivraison" value="<?=htmlspecialchars($client['ville'])?>">

<Label for="codeLivraison">code postal :</Label>
<input type="text" name="codeLivraison" value="<?=htmlspecialchars($client['CodePostal'])?>">

<Label for="adresseFacturation">adresse de facturation :</Label>
<input type="text" name="adresseFacturation" value="<?=htmlspecialchars($client['adresse'])?>">

<Label for="villeLivraison"> ville de facturation : </Label>
<input type="text" name="villeFacturation" value="<?=htmlspecialchars($client['ville'])?>">

<Label for="codeFacturation"> code postal :</Label>
<input type="text" name="codeFacturation" value="<?=htmlspecialchars($client['CodePostal'])?>">

<Label for="statut"> Facture payée ?</Label>
<input type="checkBox" name="statut">



<input type="submit">

</form>


<a href="../controllers/detailsFacture.php?id=<?= $client['id_clients'] ?>">completer la suite de la facture </a>


    
</body>
</html>
