<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>


<?php if (count($infosClient) > 0) : ?>

   
<section>

<?php foreach ($infosClient as $client) : ?>

<div>

        <h1> Fiche client </h1>

    <h1>Nom:<?= htmlspecialchars($client['nom']) ?></h1>

    <h2>Prénom:<?= htmlspecialchars($client['prenom']) ?></h2>

    <h3>Référence:<?= htmlspecialchars($client['ref_client']) ?></h3>

    <p>téléphone:<?= htmlspecialchars($client['telephone']) ?></p>

    <p>email:<?= htmlspecialchars($client['email']) ?></p>

    <p>adresse:<?= htmlspecialchars($client['adresse']) ?></p>

    <p>ville:<?= htmlspecialchars($client['ville']) ?></p>

    <p>code postal:<?= htmlspecialchars($client['CodePostal']) ?></p>

    <div>

    <h1>liste des facture appartenant au client</h1>

    </div>
    <?php if (count($client) > 0) : ?>
<a href="../controllers/listeFactureClient.php?id=<?= intval($client['id_clients']) ?>">liste des factures pour ce client </a> 
<?php endif ?>

<br>
<a href="../controllers/creationFacture2.php?id=<?= intval($client['id_clients']) ?>">créer une facture pour ce client </a> 

</div>

<?php endforeach; ?>

</section>

<?php endif ?>

</body>

</html>