<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/edition.css" rel="stylesheet">
    <title>Document</title>
</head>
<body>

<section id="facture">

<article class="fact">
<h1>FACTURE</h1>
</article>

<article class="adresseSociete">

<p><?= $recupEditionSociete['nom'] ?> <br> <?= $recupEditionSociete['adresse'] ?> <br> <?= $recupEditionSociete['telephone'] ?></p>

</article>
<article class="infosClients">
<div>
<h2>Facturé à</h2>
<p><?= $recupEditionClient['nom'] ?> <br><?= $recupEditionClient['prenom'] ?> <br> <?= $recupEditionClient['ref_client'] ?> <br><?= $recupEdition[0]['adresse_facturation'] ?> <br><?= $recupEdition[0]['codePostal_facturation'] ?>  <br><?= $recupEdition[0]['ville_facturation'] ?>  <br> <?= $recupEditionClient['telephone'] ?></p>
</div>

<div>
<h2>Envoyé à</h2>
<p>  <?= $recupEdition[0]['adresse_livraison'] ?> <br><?= $recupEdition[0]['codePostal_livraison'] ?><br><?= $recupEdition[0]['ville_livraison'] ?> </p>
</div>

<div>
<h2>FACTURE n°</h2>
<h2>DATE EMISSION</h2>
<h2>DATE RECOUVREMENT</h2>
</div>


<div>
<h2><?= $recupEdition[0]['id_facture'] ?></h2>
<h2><?= $recupEdition[0]['date_emission'] ?> </h2>
<h2><?= $recupEdition[0]['date_paiement'] ?></h2>
</div>

</article>

<article class="nom">

<h2>Quantité</h2>
<h2>Nom</h2>
<h2>Prix unitaire</h2>
<h2>TVA</h2>

</article>

<?php foreach ($recupEdition as $recupEditions):?>

<article class="article">

<h3><?= $recupEditions['quantite'] ?></h3>
<h3><?= $recupEditions['nom'] ?></h3>
<h3><?= $recupEditions['prix_unitaire'] ?>€</h3>
<h3><?= $recupEditions['TVA'] ?>%</h3>

</article>

<?php endforeach ?>

<article class="TTC">

<h2>total HT : </h2>
<h2>Total tva 5,5% :</h2>
<h2>Total tva 20% :</h2>
<h2>Montant TTC :</h2>

</article>

<article class="signature">

<h2> Signature: </h2>


</article>

</section>
    
</body>
</html>