<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

<form action='../controllers/inscriptionVendeur.php' method="$_POST">

<input type="text" placeholder="inscrivez le nom de votre employé ">

<input type="text" placeholder="inscrivez le prénom de votre employé ">

<input type="text" placeholder="inscrivez le numéro de référence de votre employé ">


</form>



</body>
</html>