<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/inscriptionSociete.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<?php/* var_dump($_POST); */?>
<section id="inscription">

<form action="../controllers/inscriptionSociete.php" method="post"> 

<input type="text" name="nom" placeholder="Nom de votre société"> 

<input type="text" name="adresse" placeholder="adresse de votre société"> 

<input type="text" name="tel" placeholder="téléphone de votre société"> 

<input type="password" name="password" placeholder="entrez un mot de passe"> 

<button type="submit" class="bouton"> S'INSCRIRE <span></span><span></span><span></span><span></span></button>

<?php if( !empty($_POST) ):?>

<p class="Login">Veuillez remplir tous les champs </p>

<?php endif ?>

</form>

</section>



</body>
</html>