<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/inscriptionVendeur.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>

    
<section id="contener">
<header>
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>
<form action='../controllers/inscriptionVendeur.php' method="post">

<input type="text" name="nom" placeholder="inscrivez le nom de votre employé ">

<input type="text" name="prenom" placeholder="inscrivez le prénom de votre employé ">

<input type="text" name="ref" placeholder="inscrivez le numéro de référence de votre employé">

<input type="text" name="email" placeholder="inscrivez l'email de votre employé">

<input type="text" name="telephone" placeholder="inscrivez le téléphone de votre vendeur">

<input type="text" name="password" placeholder="inscrivez le mot de passe qui sera utilisé par le vendeur">

<button class="bouton" type="submit"><span></span><span></span><span></span><span></span>Inscription</button>


</form>


</section>

</body>
</html>