<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

<form action='../controllers/inscriptionVendeur.php' method="post">

<input type="text" name="nom" placeholder="inscrivez le nom de votre employé ">

<input type="text" name="prenom" placeholder="inscrivez le prénom de votre employé ">

<input type="text" name="ref" placeholder="inscrivez le numéro de référence de votre employé">

<input type="text" name="email" placeholder="inscrivez l'email de votre employé">

<input type="text" name="telephone" placeholder="inscrivez le téléphone de votre vendeur">

<input type="text" name="password" placeholder="inscrivez le mot de passe qui sera utilisé par le vendeur">




</form>



</body>
</html>