<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/listeStock.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>

<body>
<section id="contener">
<header>
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>

    <?php if (count($listeStock) > 0) : ?>

        <?php foreach ($listeStock as $stock) : ?>



            <section class="vendeur">

                <h1>Nom: <?= htmlspecialchars($stock['nom_Produit']) ?></h1>

                <h2>Référence produit: <?= htmlspecialchars($stock['ref']) ?></h2>

                <h3>prix unitaire: <?= htmlspecialchars($stock['prix_unitaire']) ?></h3>

                <p>stock: <?= htmlspecialchars($stock['quantite_stock']) ?></p>


                <a class="bouton" href="../controllers/modifStock.php?id=<?= intval($stock['id_stock']) ?>"><span></span><span></span><span></span><span></span>modifier les informations du produit</a>


                <a class="bouton" href="../controllers/suppStock.php?id=<?= intval($stock['id_stock']) ?>"><span></span><span></span><span></span><span></span>Supprimer le produit</a>

                <div class="border"></div>
              
            <?php endforeach ?>

           

        <?php endif ?>

        </section>


        </section>

</body>

</html>