<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/listeFactureClient.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<section id="contener">
<header>
<a href="../controllers/pageConnecteeVendeur.php"><i class="fas fa-home"></i></a>

</header>    

<section class="vendeur">
<?php if(count($liste)>0) :?> 

<h3><?=htmlspecialchars($liste['nom'])?></h3>
<h4><?=htmlspecialchars($liste['prenom'])?></h4>
<p><?= htmlspecialchars($liste['ref_client'])?></p>
<p><?= htmlspecialchars($liste['telephone'])?></p>
<p><?= htmlspecialchars($liste['date_emission'])?></p>
<p><?= htmlspecialchars($liste['date_paiement'])?></p>
<p><?= htmlspecialchars($liste['adresse_livraison'])?></p>
<p><?= htmlspecialchars($liste['ville_livraison'])?></p>
<p><?= htmlspecialchars($liste['codePostal_livraison'])?></p>
<p><?= htmlspecialchars($liste['adresse_facturation'])?></p>
<p><?= htmlspecialchars($liste['ville_facturation'])?></p>
<p><?= htmlspecialchars($liste['codePostal_facturation'])?></p>

<a class="bouton" href="../controllers/suppFacture.php?id=<?= intval($liste['id_facture'])?>"> <span></span><span></span><span></span><span></span>supprimer la facture</a>
<a class="bouton" href="../controllers/modifListeFacture.php?id=<?= intval($liste['id_facture'])?>"> <span></span><span></span><span></span><span></span>modifier la facture</a>
<div class="border"></div>
<h2>Les produits affectés à cette facture</h2>
<?php if(count($objet)>0) :?>
<?php foreach($objet as $objets) :?>

    <h3><?= htmlspecialchars($objets['nom'])?></h3>
    <p>quantité:<?= htmlspecialchars($objets['quantite'])?></p>
    <p>prix unitaire: <?= htmlspecialchars($objets['prix_unitaire'])?> €</p>
    <p>TVA: <?= htmlspecialchars($objets['TVA'])?> %</p>
    <a class="bouton" href="../controllers/modifProduitFactureDetails.php?id=<?= intval($objets['id_factureDetails']) ?>"><span></span><span></span><span></span><span></span>modifier ce produit sur la facture</a>
    <a class="bouton" href="../controllers/suppProduitFactureDetails.php?id=<?= intval($objets['id_factureDetails']) ?>"><span></span><span></span><span></span><span></span>supprimer ce produit sur la facture</a>
    <div class="border"></div>
<?php endforeach ?>
<?php endif ?> 

<a class="bouton" href="../controllers/ajoutProduitFacture.php?id=<?= intval($liste['id_facture']) ?> & idSoc=<?= intval($liste['id_societes']) ?>"><span></span><span></span><span></span><span></span>ajouter des produits à cette facture</a>

<a class="bouton" href="../controllers/editionFacture.php?id=<?= intval($liste['id_facture']) ?>"><span></span><span></span><span></span><span></span>éditer cette facture</a>

<?php endif ?> 
</section>
</section>

</body>
</html>