<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <?php if (count($listeStock) > 0) : ?>

        <?php foreach ($listeStock as $stock) : ?>



            <section>

                <h1>Nom:<?= htmlspecialchars($stock['nom_Produit']) ?></h1>

                <h2>Référence produit:<?= htmlspecialchars($stock['ref']) ?></h2>

                <h3>prix unitaire:<?= htmlspecialchars($stock['prix_unitaire']) ?></h3>

                <p>stock:<?= htmlspecialchars($stock['quantite_stock']) ?></p>


                <a href="../controllers/modifStock.php?id=<?= intval($stock['id_stock']) ?>">modifier les informations du produit</a>


                <a href="../controllers/suppStock.php?id=<?= intval($stock['id_stock']) ?>">Supprimer le produit</a>


              
            <?php endforeach ?>

            </section>

        <?php endif ?>






</body>

</html>