<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <?php if (count($listeVendeur) > 0) : ?>

        <?php foreach ($listeVendeur as $vendeur) : ?>



            <section>

                <h1>Nom:<?= htmlspecialchars($vendeur['nom_vendeur']) ?></h1>

                <h2>Prénom:<?= htmlspecialchars($vendeur['prenom_vendeur']) ?></h2>

                <h3>Référence:<?= htmlspecialchars($vendeur['ref_vendeur']) ?></h3>

                <p>email:<?= htmlspecialchars($vendeur['email']) ?></p>

                <p>téléphone:<?= htmlspecialchars($vendeur['telephone_vendeur']) ?></p>

                <a href="../controllers/modifVendeur.php?id=<?= intval($vendeur['id_vendeur']) ?>">modifier les informations du vendeur</a>


                <a href="../controllers/suppVendeur.php?id=<?= intval($vendeur['id_vendeur']) ?>">Supprimer le vendeur</a>


            <?php endforeach; ?>

            </section>

        <?php endif; ?>






</body>

</html>