<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<?php if(count($liste)>0) :?> 

<h3><?=htmlspecialchars($liste['nom'])?></h3>
<h4><?=htmlspecialchars($liste['prenom'])?></h4>
<p><?= htmlspecialchars($liste['ref_client'])?></p>
<p><?= htmlspecialchars($liste['telephone'])?></p>
<p><?= htmlspecialchars($liste['date_emission'])?></p>
<p><?= htmlspecialchars($liste['date_paiement'])?></p>
<p><?= htmlspecialchars($liste['adresse_livraison'])?></p>
<p><?= htmlspecialchars($liste['ville_livraison'])?></p>
<p><?= htmlspecialchars($liste['codePostal_livraison'])?></p>
<p><?= htmlspecialchars($liste['adresse_facturation'])?></p>
<p><?= htmlspecialchars($liste['ville_facturation'])?></p>
<p><?= htmlspecialchars($liste['codePostal_facturation'])?></p>

<a href="../controllers/suppFacture.php?id=<?= intval($liste['id_facture'])?>">supprimer la facture</a>
<a href="../controllers/modifListeFacture.php?id=<?= intval($liste['id_facture'])?>">modifier la facture</a>

<h2>Les produits affectés à cette facture</h2>
<?php if(count($objet)>0) :?>
<?php foreach($objet as $objets) :?>

    <h3><?= htmlspecialchars($objets['nom'])?></h3>
    <p>quantité:<?= htmlspecialchars($objets['quantite'])?></p>
    <p>prix unitaire: <?= htmlspecialchars($objets['prix_unitaire'])?> €</p>
    <p>TVA: <?= htmlspecialchars($objets['TVA'])?> %</p>
    <a href="../controllers/modifProduitFactureDetails.php?id=<?= intval($objets['id_factureDetails']) ?>">modifier ce produit sur la facture</a>
    <a href="../controllers/suppProduitFactureDetails.php?id=<?= intval($objets['id_factureDetails']) ?>">supprimer ce produit sur la facture</a>
<?php endforeach ?>
<?php endif ?> 

<a href="../controllers/ajoutProduitFacture.php?id=<?= intval($liste['id_facture']) ?> & idSoc=<?= intval($liste['id_societes']) ?>">ajouter des produits à cette facture</a>

<a href="../controllers/editionFacture.php?id=<?= intval($liste['id_facture']) ?>">éditer cette facture</a>

<?php endif ?> 

</body>
</html>