<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <?php if (count($listeClient) > 0) : ?>

        <?php foreach ($listeClient as $client) : ?>



            <section>

                <h1>Nom:<?= htmlspecialchars($client)['nom'] ?></h1>

                <h2>Prénom:<?= htmlspecialchars($client)['prenom'] ?></h2>

                <h3>Référence:<?= htmlspecialchars($client)['ref_client'] ?></h3>

                <p>téléphone:<?= htmlspecialchars($client)['telephone'] ?></p>

                <p>email:<?= htmlspecialchars($client)['email'] ?></p>

                <p>adresse:<?= htmlspecialchars($client)['adresse'] ?></p>

                <p>ville:<?= htmlspecialchars($client)['ville'] ?></p>

                <p>code postal:<?= htmlspecialchars($client)['CodePostal'] ?></p>


                <a href="../controllers/modifClient.php?id=<?= intval($client['id_clients']) ?>">modifier les informations du client</a>


                <a href="../controllers/suppClient.php?id=<?= intval($client['id_clients']) ?>">Supprimer le client</a>


            <?php endforeach; ?>

            </section>

        <?php endif; ?>






</body>

</html>