<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/listeVendeur.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>

<body>

<section id="contener">
<header>
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>

    <?php if (count($listeVendeur) > 0) : ?>

        <?php foreach ($listeVendeur as $vendeur) : ?>



            <section class="vendeur">

                <h1>Nom: <?= htmlspecialchars($vendeur['nom_vendeur']) ?></h1>

                <h2>Prénom: <?= htmlspecialchars($vendeur['prenom_vendeur']) ?></h2>

                <h3>Référence: <?= htmlspecialchars($vendeur['ref_vendeur']) ?></h3>

                <p>email: <?= htmlspecialchars($vendeur['email']) ?></p>

                <p>téléphone: <?= htmlspecialchars($vendeur['telephone_vendeur']) ?></p>

                <a class="bouton" href="../controllers/modifVendeur.php?id=<?= intval($vendeur['id_vendeur']) ?>"><span></span><span></span><span></span><span></span>modifier les informations du vendeur</a>


                <a class="bouton" href="../controllers/suppVendeur.php?id=<?= intval($vendeur['id_vendeur']) ?>"><span></span><span></span><span></span><span></span>Supprimer le vendeur</a>

                <div class="border"></div>

            <?php endforeach; ?>

            

        <?php endif; ?>

        </section>



        </section>


</body>

</html>