<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/modifListeFacture.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>

<section id="contener">
<header>
    
<a href="../controllers/pageConnecteeVendeur.php"><i class="fas fa-home"></i></a>

</header>


<form action="../controllers/modifListeFacture.php?id=<?= $client['id_facture'] ?>" method="post">




<input type="date" name="datePaiement" value="<?=htmlspecialchars($client['date_paiement'])?>">

<textarea name="commentaire"><?=htmlspecialchars($client['commentaire'])?></textarea>

<Label for="adresseLivraison"> adresse Livraison :</Label>
<input type="text" name="adresseLivraison" value="<?=htmlspecialchars($client['adresse_livraison'])?>">


<input type="text" name="villeLivraison" value="<?=htmlspecialchars($client['ville_livraison'])?>">

<input type="text" name="codeLivraison" value="<?=htmlspecialchars($client['codePostal_livraison'])?>">

<Label for="adresseFacturation"> adresse Facturation :</Label>
<input type="text" name="adresseFacturation" value="<?=htmlspecialchars($client['adresse_facturation'])?>">


<input type="text" name="villeFacturation" value="<?=htmlspecialchars($client['ville_facturation'])?>">

<input type="text" name="codeFacturation" value="<?=htmlspecialchars($client['codePostal_facturation'])?>">

<div class="statut">
<Label for="statut"> Facture payée ?</Label>
<input type="checkBox" name="statut" <?=htmlspecialchars($client['statut'])?>>
</div>

<button class="bouton" type="submit"><span></span><span></span><span></span><span></span>Modifier</button>

</form>

</section>

    
</body>
</html>