<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/modifStock.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<section id="contener">
<header>
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>
    
<?php if(count($placeHolder)>0) :?>

<?php foreach($placeHolder as $holder) :?> 

    
   

<form action='../controllers/modifStock.php?id=<?= $_GET["id"] ?>' method="post">

<input type="text" name="quantite" value="<?= htmlspecialchars($holder['quantite_stock'])?>" placeholder="inscrivez la quantité du produit">

<input type="text" name="nom" value="<?= htmlspecialchars($holder['nom_Produit'])?>" placeholder="inscrivez le nom du produit">

<input type="text" name="ref"value="<?= htmlspecialchars($holder['ref'])?>" placeholder="inscrivez la référence du produit">

<input type="text" name="prixUnitaire" value="<?= htmlspecialchars($holder['prix_unitaire'])?>"placeholder="inscrivez le prix unitaire">

<button class="bouton" type="submit"><span></span><span></span><span></span><span></span>Modifier</button>

<?php endforeach ?>

<?php endif ?>

</form>

  


</section>


</body>
</html>