<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<form action='../controllers/modifDetails2.php?id=<?= $modifDetailsFacture['id_factureDetails'] ?>' method="post">

<input type="text" name="quantite" placeholder="inscrivez la quantité du produit" value="<?= $modifDetailsFacture['quantite'] ?>">

<input type="text" name="tva" placeholder="inscrivez la TVA" value="<?= $modifDetailsFacture['TVA'] ?>">

<input type="text" name="prixUnitaire" placeholder="inscrivez le prix unitaire" value="<?= $modifDetailsFacture['prix_unitaire'] ?>">

<input type="submit">


</form>

</body>
</html>