<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/modifVendeur.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<section id="contener">
<header>
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>


<?php if(count($placeHolder)>0) :?>

<?php foreach($placeHolder as $holder) :?>
    

<form action='../controllers/modifVendeur.php?id=<?= $_GET["id"] ?>' method="post">

<input type="text" name="nom" value="<?= htmlspecialchars($holder['nom_vendeur']) ?>" placeholder="inscrivez le nom de votre employé ">

<input type="text" name="prenom" value="<?= htmlspecialchars($holder['prenom_vendeur']) ?>" placeholder="inscrivez le prénom de votre employé ">

<input type="text" name="ref" value="<?= htmlspecialchars($holder['ref_vendeur']) ?>" placeholder="inscrivez le numéro de référence de votre employé">

<input type="text" name="email" value="<?= htmlspecialchars($holder['email']) ?>" placeholder="inscrivez l'email de votre employé">

<input type="text" name="telephone" value="<?= htmlspecialchars($holder['telephone_vendeur']) ?>" placeholder="inscrivez le téléphone de votre vendeur">

<input type="password" name="password"  placeholder="inscrivez le mot de passe qui sera utilisé par le vendeur">

<button class="bouton" type="submit"><span></span><span></span><span></span><span></span>Modifier</button>


<?php endforeach ?>

<?php endif ?>

</form>

</section>


</body>
</html>