<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<?php if(count($placeHolder)>0) :?>

<?php foreach($placeHolder as $holder) :?> 

<form action='../controllers/modifStock.php?id=<?= $_GET["id"] ?>' method="post">

<input type="text" name="quantite" value="<?= htmlspecialchars($holder['quantite_stock'])?>" placeholder="inscrivez la quantité du produit">

<input type="text" name="nom" value="<?= htmlspecialchars($holder['nom_Produit'])?>" placeholder="inscrivez le nom du produit">

<input type="text" name="ref"value="<?= htmlspecialchars($holder['ref'])?>" placeholder="inscrivez la référence du produit">

<input type="text" name="prixUnitaire" value="<?= htmlspecialchars($holder['prix_unitaire'])?>"placeholder="inscrivez le prix unitaire">

<input type="submit">

<?php endforeach ?>

<?php endif ?>

</form>


<a href="../controllers/pageConnecteeSociete.php">home</a>


</body>
</html>