<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/modifProduitFactureDetails.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>

<section id="contener">
<header>
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>
    
<form action='../controllers/modifDetails2.php?id=<?= htmlspecialchars($modifDetailsFacture['id_factureDetails']) ?>' method="post">

<input type="text" name="quantite" placeholder="inscrivez la quantité du produit" value="<?= htmlspecialchars($modifDetailsFacture['quantite']) ?>">

<input type="text" name="tva" placeholder="inscrivez la TVA" value="<?= htmlspecialchars($modifDetailsFacture['TVA']) ?>">

<input type="text" name="prixUnitaire" placeholder="inscrivez le prix unitaire" value="<?= htmlspecialchars($modifDetailsFacture['prix_unitaire']) ?>">

<button class="bouton" type="submit"><span></span><span></span><span></span><span></span>Modifier</button>


</form>
</section>
</body>
</html>