<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<form action="../controllers/modifList.php?id=<?= $client['id_facture'] ?>" method="post">



<Label for="datePaiement"> date de paiement prevu : </Label>
<input type="date" name="datePaiement" value="<?=htmlspecialchars($client['date_paiement'])?>">

<textarea name="commentaire"><?=htmlspecialchars($client['commentaire'])?></textarea>

<Label for="adresseLivraison">adresse de livraison :</Label>
<input type="text" name="adresseLivraison" value="<?=htmlspecialchars($client['adresse_livraison'])?>">

<Label for="villeLivraison">ville de livraison :</Label>
<input type="text" name="villeLivraison" value="<?=htmlspecialchars($client['ville_livraison'])?>">

<Label for="codeLivraison">code postal :</Label>
<input type="text" name="codeLivraison" value="<?=htmlspecialchars($client['codePostal_livraison'])?>">

<Label for="adresseFacturation">adresse de facturation :</Label>
<input type="text" name="adresseFacturation" value="<?=htmlspecialchars($client['adresse_facturation'])?>">

<Label for="villeLivraison"> ville de facturation : </Label>
<input type="text" name="villeFacturation" value="<?=htmlspecialchars($client['ville_facturation'])?>">

<Label for="codeFacturation"> code postal :</Label>
<input type="text" name="codeFacturation" value="<?=htmlspecialchars($client['codePostal_facturation'])?>">

<Label for="statut"> Facture payée ?</Label>
<input type="checkBox" name="statut" <?=htmlspecialchars($client['statut'])?>>



<input type="submit">

</form>

    
</body>
</html>