<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/modifClient.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<section id="contener">
<header>
<a href="../controllers/pageConnecteeSociete.php"><i class="fas fa-home"></i></a>

</header>

<form action="../controllers/modifClient.php?id=<?= htmlspecialchars($_GET["id"]) ?>" method="post"> 

<?php foreach($placeHolder as $holder) :?>

<input type="text" name="nom" value="<?= htmlspecialchars($holder['nom'])?>" placeholder="inserez le nom de votr client "> 

<input type="text" name="prenom" value="<?= htmlspecialchars($holder['prenom'])?>" placeholder="inserez le prenom de votr client "> 

<input type="text" name="telephone" value="<?= htmlspecialchars($holder['telephone'])?>" placeholder="numéro de téléphone du client"> 

<input type="text" name="ref" value="<?= htmlspecialchars($holder['ref_client'])?>"placeholder="référence client">

<input type="text" name="email"  value="<?= htmlspecialchars($holder['email'])?>" placeholder="e-mail du client">

<input type="text" name="adresse" value="<?= htmlspecialchars($holder['adresse'])?>" placeholder="adresse du client"> 

<input type="text" name="ville" value="<?= htmlspecialchars($holder['ville'])?>" placeholder="ville du client"> 

<input type="text" name="codePostal" value="<?= htmlspecialchars($holder['CodePostal'])?>" placeholder="codePostal du client"> 


<?php endforeach ?>

<button class="bouton" type="submit"><span></span><span></span><span></span><span></span>Modifier</button>



</form>

</section>

</body>
</html>