<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="../controllers/modifClient.php?id=<?= $_GET["id"] ?>" method="post"> 

<?php foreach($placeHolder as $holder) :?>

<input type="text" name="nom" value="<?= htmlspecialchars($holder['nom'])?>" placeholder="inserez le nom de votr client "> 

<input type="text" name="prenom" value="<?= htmlspecialchars($holder['prenom'])?>" placeholder="inserez le prenom de votr client "> 

<input type="text" name="telephone" value="<?= htmlspecialchars($holder['telephone'])?>" placeholder="numéro de téléphone du client"> 

<input type="text" name="ref" value="<?= htmlspecialchars($holder['ref_client'])?>"placeholder="référence client">

<input type="text" name="email"  value="<?= htmlspecialchars($holder['email'])?>" placeholder="e-mail du client">

<input type="text" name="adresse" value="<?= htmlspecialchars($holder['adresse'])?>" placeholder="adresse du client"> 

<input type="text" name="ville" value="<?= htmlspecialchars($holder['ville'])?>" placeholder="ville du client"> 

<input type="text" name="codePostal" value="<?= htmlspecialchars($holder['CodePostal'])?>" placeholder="codePostal du client"> 


<?php endforeach ?>

<input type="submit">


</form>

<a href="../controllers/pageConnecteeSociete.php">home</a>

</body>
</html>