<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/pageConnecteeSociete.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <section id="contener">
    <a class="bouton" href="../controllers/deco.php"><span></span><span></span><span></span><span></span>deconnection</a>
    <a class="bouton" href="../controllers/inscriptionVendeur.php"><span></span><span></span><span></span><span></span>inscription d'un vendeur dans votre société</a>
    <a class="bouton" href="../controllers/listeVendeur.php"><span></span><span></span><span></span><span></span>liste des vendeurs dans votre societe </a>
    <a class="bouton" href="../controllers/ajoutStock.php"><span></span><span></span><span></span><span></span>ajouter un produit en stock</a>
    <a class="bouton" href="../controllers/listeStock.php"><span></span><span></span><span></span><span></span>liste des produits</a>
    <a class="bouton" href="../controllers/ajoutClient.php"><span></span><span></span><span></span><span></span>ajouter un client a la société</a>
    <a class="bouton" href="../controllers/listeClient.php"><span></span><span></span><span></span><span></span>liste des clients de la société</a>
    </section>
</body>
</html>