<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/pageConnecteeVendeur.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>
<section id="contener">

   <a class="bouton" href="../controllers/decoVendeur.php"><span></span><span></span><span></span><span></span>deconnection</a>
   <a class="bouton" href="../controllers/creationFacture.php"><span></span><span></span><span></span><span></span> creation d'une facture </a>
   
</section>
</body>
</html>