<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="../controllers/deco.php">deconnection</a>
    <a href="../controllers/inscriptionVendeur.php">inscription d'un vendeur dans votre société</a>
    <a href="../controllers/listeVendeur.php">liste des vendeurs dans votre societe </a>
    <a href="../controllers/ajoutStock.php">ajouter un produit en stock</a>
    <a href="../controllers/listeStock.php">liste des produits</a>
    <a href="../controllers/ajoutClient.php">ajouter un client a la société</a>
    <a href="../controllers/listeClient.php">liste des clients de la société</a>

</body>
</html>