<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<h1>Produit selectioné: <?=$recupObjetSelect['nom_Produit']?> </h1>


<form method="post" action="../controllers/ajoutLigneFacture.php?idFacture=<?=$_GET["idFacture"] ?>">

<label for="nom">dénomination</label>
<select name="nom">
<option   value="<?=htmlspecialchars($recupObjetSelect['nom_Produit'])?>"><?=htmlspecialchars($recupObjetSelect['nom_Produit'])?></option>
</select>

<label for="quantite">stock maximal</label>
<input type="text" name="quantite" placeholder="<?=htmlspecialchars($recupObjetSelect['quantite_stock'])?>">

<label for="prixUnitaire">prix unitaire</label>
<input type="text" name="prix" value="<?=htmlspecialchars($recupObjetSelect['prix_unitaire'])?>">

<label for="tva">tva</label>
<select name="tva">
<option >5,5%</option>
<option >20%</option>
</select>

<input type="submit" value="envoyer">

</form>
</body>
</html>