<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="../assets/recupObjetSelect.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/2dc5983f48.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>


<section id="contener">
<header>
<a href="../controllers/pageConnecteeVendeur.php"><i class="fas fa-home"></i></a>

</header>

<h1>Produit selectioné: <?=htmlspecialchars($recupObjetSelect['nom_Produit'])?> </h1>


<form method="post" action="../controllers/ajoutLigneFacture.php?idFacture=<?=htmlspecialchars($_GET["idFacture"]) ?>">

<label for="nom">dénomination</label>
<select name="nom">
<option   value="<?=htmlspecialchars($recupObjetSelect['nom_Produit'])?>"><?=htmlspecialchars($recupObjetSelect['nom_Produit'])?></option>
</select>

<label for="quantite">stock maximal</label>
<input type="text" name="quantite" placeholder="<?=htmlspecialchars($recupObjetSelect['quantite_stock'])?>">

<label for="prixUnitaire">prix unitaire</label>
<input type="text" name="prix" value="<?=htmlspecialchars($recupObjetSelect['prix_unitaire'])?>">

<label for="tva">tva</label>
<select name="tva">
<option >5,5%</option>
<option >20%</option>
</select>

<button class="bouton" type="submit" ><span></span><span></span><span></span><span></span>Ajouter</button>

</section>

</form>
</body>
</html>